inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'tmp/**/**/*'
    - 'lib/**/*'
    - '**/Gemfile'
    - '**/Guardfile'
  DisplayStyleGuide: true
  DisplayCopNames: true

Metrics/MethodLength:
  Max: 25

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 150

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/RegexpLiteral:
  EnforcedStyle: slashes
