inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'tmp/**/**/*'
    - 'lib/**/*'
    - '**/Gemfile'
    - '**/Guardfile'
  DisplayStyleGuide: true
  DisplayCopNames: true

Metrics/MethodLength:
  Max: 25

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 150
  Exclude:
    - 'spec/**/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/RegexpLiteral:
  EnforcedStyle: slashes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/records_helper.rb'
    - 'spec/**/*'
