# The Supplejack Worker code is Crown copyright (C) 2014, New Zealand Government,
# and is licensed under the GNU General Public License, version 3.
# See https://github.com/DigitalNZ/supplejack_worker for details.
#
# Supplejack was created by DigitalNZ at the National Library of NZ
# and the Department of Internal Affairs. http://digitalnz.org/supplejack

development:
  clients:
    default:
      database: worker_development
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:

    api:
      database: dnz_api_development
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        read:
          mode: :nearest
  options:

test:
  clients:
    default:
      database: worker_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :nearest
        max_retries: 1
        retry_interval: 0
    api:
      database: dnz_api_test
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        read:
          mode: :nearest

staging:
  clients:
    default:
      database: worker_staging
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        pool_size: 500
    api:
      database: dnz_api_staging
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        read:
          mode: :primary
        pool_size: 500

production:
  clients:
    default:
      database: worker_production
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        read:
          mode: :primary
        pool_size: 500
    api:
      database: dnz_api_production
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        read:
          mode: :primary_preferred
        pool_size: 500

