
development:
  clients:
    default:
      database: worker_development
      hosts:
        - <%= ENV['MONGOID_HOST'] || 'localhost:27017' %>
      options:

    api:
      database: dnz_api_development
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        read:
          mode: :nearest
  options:

test:
  clients:
    default:
      database: worker_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :nearest
        max_retries: 1
        retry_interval: 0
    api:
      database: dnz_api_test
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        read:
          mode: :nearest

staging:
  clients:
    default:
      database: worker_staging
      hosts:
        - <%= ENV['MONGOID_HOST'] || 'localhost:27017' %>
      options:
        read:
          mode: :primary
        pool_size: 500
        user: <%= ENV['MONGOID_USER'] %>
        password: <%= ENV['MONGOID_PASSWORD'] %>
        auth_source: admin
        ssl: <%= ENV['MONGOID_SSL_ENABLED'] || false %>
        ssl_cert: <%= ENV['MONGOID_SSL_CERT_PATH'] %>
        ssl_key: <%= ENV['MONGOID_SSL_CERT_PATH'] %>
        ssl_verify: <%= ENV['MONGOID_SSL_ENABLED'] || false %>
        ssl_ca_cert: <%= ENV['MONGOID_SSL_CA_CERT_PATH'] %>
    api:
      database: dnz_api_staging
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        read:
          mode: :primary
        pool_size: 500
        user: <%= ENV['MONGOID_USER'] %>
        password: <%= ENV['MONGOID_PASSWORD'] %>
        auth_source: admin
        ssl: <%= ENV['MONGOID_SSL_ENABLED'] || false %>
        ssl_cert: <%= ENV['MONGOID_SSL_CERT_PATH'] %>
        ssl_key: <%= ENV['MONGOID_SSL_CERT_PATH'] %>
        ssl_verify: <%= ENV['MONGOID_SSL_ENABLED'] || false %>
        ssl_ca_cert: <%= ENV['MONGOID_SSL_CA_CERT_PATH'] %>
production:
  clients:
    default:
      database: worker_production
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        read:
          mode: :primary
        pool_size: 500
    api:
      database: dnz_api_production
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        read:
          mode: :primary_preferred
        pool_size: 500
