default:
  clients:
    default:
      database: worker_uat
      hosts: <%= ENV.fetch('MONGO_HOSTS', 'localhost:27017').gsub(/\s+/, '')&.split(',') %>
      options:
        read:
          mode: :primary
        auth_source: admin
        max_pool_size: 500
        user: <%= ENV['MONGO_USER'] %>
        password: <%= ENV['MONGO_PASSWORD'] %>
    api:
      database: dnz_api_uat
      hosts: <%= ENV.fetch('MONGO_HOSTS', 'localhost:27017').gsub(/\s+/, '')&.split(',') %>
      options:
        read:
          mode: :primary
        auth_source: admin
        max_pool_size: 500
        user: <%= ENV['MONGO_USER'] %>
        password: <%= ENV['MONGO_PASSWORD'] %>

development:
  clients:
    default:
      database: worker_development
      hosts: <%= ENV.fetch('MONGO_HOSTS', 'localhost:27017').gsub(/\s+/, '')&.split(',') %>
      options:

    api:
      database: dnz_api_development
      hosts: <%= ENV.fetch('MONGO_HOSTS', 'localhost:27017').gsub(/\s+/, '')&.split(',') %>
      options:
        read:
          mode: :nearest
  options:

test:
  clients:
    default:
      database: worker_test
      hosts: <%= ENV.fetch('MONGO_HOSTS', 'localhost:27017').gsub(/\s+/, '')&.split(',') %>
      options:
        read:
          mode: :nearest
        max_retries: 1
        retry_interval: 0
    api:
      database: dnz_api_test
      hosts: <%= ENV.fetch('MONGO_HOSTS', 'localhost:27017').gsub(/\s+/, '')&.split(',') %>
      options:
        read:
          mode: :nearest

uat:
  clients:
    default:
      database: worker_uat
      hosts: <%= ENV.fetch('MONGO_HOSTS', 'localhost:27017').gsub(/\s+/, '')&.split(',') %>
      options:
        read:
          mode: :primary
        auth_source: admin
        max_pool_size: 500
        user: <%= ENV['MONGO_USER'] %>
        password: <%= ENV['MONGO_PASSWORD'] %>
    api:
      database: dnz_api_uat
      hosts: <%= ENV.fetch('MONGO_HOSTS', 'localhost:27017').gsub(/\s+/, '')&.split(',') %>
      options:
        read:
          mode: :primary
        auth_source: admin
        max_pool_size: 500
        user: <%= ENV['MONGO_USER'] %>
        password: <%= ENV['MONGO_PASSWORD'] %>
staging:
  clients:
    default:
      database: worker_staging
      hosts: <%= ENV.fetch('MONGO_HOSTS', 'localhost:27017').gsub(/\s+/, '')&.split(',') %>
      options:
        read:
          mode: :primary
        auth_source: admin
        max_pool_size: 500
        user: <%= ENV['MONGO_USER'] %>
        password: <%= ENV['MONGO_PASSWORD'] %>
    api:
      database: dnz_api_staging
      hosts: <%= ENV.fetch('MONGO_HOSTS', 'localhost:27017').gsub(/\s+/, '')&.split(',') %>
      options:
        read:
          mode: :primary
        auth_source: admin
        max_pool_size: 500
        user: <%= ENV['MONGO_USER'] %>
        password: <%= ENV['MONGO_PASSWORD'] %>

production:
  clients:
    default:
      database: worker_production
      hosts: <%= ENV.fetch('MONGO_HOSTS', 'localhost:27017').gsub(/\s+/, '')&.split(',') %>
      options:
        read:
          mode: :primary
        auth_source: admin
        max_pool_size: 500
        user: <%= ENV['MONGO_USER'] %>
        password: <%= ENV['MONGO_PASSWORD'] %>
    api:
      database: dnz_api_production
      hosts: <%= ENV.fetch('MONGO_HOSTS', 'localhost:27017').gsub(/\s+/, '')&.split(',') %>
      options:
        auth_source: admin
        read:
          mode: :primary_preferred
        max_pool_size: 500
        user: <%= ENV['MONGO_USER'] %>
        password: <%= ENV['MONGO_PASSWORD'] %>
        connect: direct
