default: &default
  clients:
    default:
      hosts: <%= ENV.fetch('MONGO_HOSTS', 'localhost:27017').gsub(/\s+/, '')&.split(',') %>
      database: <%= ENV.fetch('MONGO_DATABASE', "worker_#{Rails.env}") %>
      options:
        auth_source: admin
        user: <%= ENV.fetch('MONGO_USER', nil) %>
        password: <%= ENV.fetch('MONGO_PASSWORD', nil) %>
        connect: <%= ENV['MONGO_CONNECT_MODE'] %>
        max_pool_size: <%= ENV.fetch('MONGO_MAX_POOL_SIZE', 500).to_i %>
        read:
          mode: <%= ENV.fetch('MONGO_READ_MODE', 'primary').to_sym %>

development:
  <<: *default

test:
  <<: *default

uat:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
