# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4b5e778af6522d58fffe3fe9489f8fa8239a06e5e00299320c3947dc812e7ed9b96475c2e2ba54c4ef3c6c4532b160d38c4703e698cb8aaf7ee54a139e330ac9

test:
  secret_key_base: 7f9f676c0dbcd76adaf9234568e9feae2d533781394ff52b63026cc3ec7e55ed187d687dbbe7cc98bc27ef51dd5d057d87fb1b6f7e4b5842c7ba73095581bc52

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
