# The Supplejack Worker code is Crown copyright (C) 2014, New Zealand Government, 
# and is licensed under the GNU General Public License, version 3. 
# See https://github.com/DigitalNZ/supplejack_worker for details. 
# 
# Supplejack was created by DigitalNZ at the National Library of NZ
# and the Department of Internal Affairs. http://digitalnz.org/supplejack

---
:verbose: true
:pidfile: ./tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
production:
  :concurrency: 25
:queues:
  - [critical, 2]
  - default
  - low
